name: base
description: Base App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Icons
  font_awesome_flutter: ^8.8.1

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.8

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.5

  # A powerful Http client for Dart
  dio: ^3.0.9

  # Request cache
  dio_http_cache: ^0.2.8

  # Helps you define global variables that can be used in the application
  flutter_dotenv: ^2.1.0

  # State Management
  flutter_bloc: ^5.0.1

  # Dependency injection
  get_it: ^4.0.2

  # Database
  sqflite: ^1.3.0+2

  # File System
  path_provider: ^1.6.11

  # Form Builder
  flutter_form_builder: ^3.11.5

  # Flush Message
  flushbar: ^1.10.4

  # Launching a URL in the mobile platform
  url_launcher: ^5.5.0

  # Querying information about an application package.
  package_info: ^0.4.0+18

  # Share Content
  share: ^0.6.4+3

  # Firebase Messaging
  firebase_messaging: ^6.0.16

  # Audio Service
  just_audio: ^0.2.2

  # Audio Service for Background
  audio_service: ^0.11.2

  # Shimmer effect
  shimmer: ^1.1.1

  # Network Image Cache
  cached_network_image: ^2.2.0+1

  # Admob
  admob_flutter: ^1.0.0-beta.5

  # Slider Up Panel
  sliding_up_panel: ^1.0.2

  # Device Locale
  devicelocale: ^0.3.1

  # Carousel Slider
  carousel_slider: ^2.2.1

  # Rx Dart
  rxdart: ^0.24.1

  # Html
  flutter_html: ^1.0.0

  # Android Alarm Managger
  android_alarm_manager: ^0.4.5+11

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_svg: ^0.18.0
  flutter_chips_input: ^1.9.0-dev.2


flutter_icons:
  image_path: "assets/images/logo.jpg"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico_regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  main_locale: fr