// Language List
Map<String, String> supportedLanguages = {
  "ach": "Acholi",
  "af": "Afrikaans",
  "an": "aragonés",
  "ar": "عربي",
  "as": "অসমীয়া",
  "ast": "Asturianu",
  "az": "Azərbaycanca",
  "be": "Беларуская",
  "bg": "Български",
  "bn": "বাংলা",
  "br": "Brezhoneg",
  "bs": "Bosanski",
  "ca": "Català",
  "cs": "Čeština",
  "cy": "Cymraeg",
  "da": "Dansk",
  "de": "Deutsch",
  "dsb": "Dolnoserbšćina",
  "el": "Ελληνικά",
  "en": "English",
  "eo": "Esperanto",
  "es": "Español",
  "et": "Eesti keel",
  "eu": "Euskara",
  "fa": "فارسی",
  "ff": "Pulaar-Fulfulde",
  "fi": "suomi",
  "fr": "Français",
  "fy": "Frysk",
  "ga": "Gaeilge",
  "gd": "Gàidhlig",
  "gl": "Galego",
  "gn": "Avañe'ẽ",
  "gu": "ગુજરાતી (ભારત)",
  "he": "עברית",
  "hi": "हिन्दी (भारत)",
  "hr": "Hrvatski",
  "hsb": "Hornjoserbsce",
  "hu": "magyar",
  "hy": "Հայերեն",
  "id": "Bahasa Indonesia",
  "is": "íslenska",
  "it": "Italiano",
  "ja": "日本語",
  "kk": "Қазақ",
  "km": "ខ្មែរ",
  "kn": "ಕನ್ನಡ",
  "ko": "한국어",
  "lij": "Ligure",
  "lt": "lietuvių kalba",
  "lv": "Latviešu",
  "mai": "मैथिली মৈথিলী",
  "mk": "Македонски",
  "ml": "മലയാളം",
  "mr": "मराठी",
  "ms": "Melayu",
  "nb": "Norsk bokmål",
  "nl": "Nederlands",
  "nn": "Norsk nynorsk",
  "or": "ଓଡ଼ିଆ",
  "pa": "ਪੰਜਾਬੀ (ਭਾਰਤ)",
  "pl": "Polski",
  "pt": "Português",
  "rm": "rumantsch",
  "ro": "Română",
  "ru": "Русский",
  "si": "සිංහල",
  "sk": "slovenčina",
  "sl": "Slovenščina",
  "son": "Soŋay",
  "sq": "Shqip",
  "sr": "Српски",
  "sv": "Svenska",
  "ta": "தமிழ்",
  "te": "తెలుగు",
  "th": "ไทย",
  "tr": "Türkçe",
  "uk": "Українська",
  "uz": "Oʻzbek tili",
  "vi": "Tiếng Việt",
  "xh": "isiXhosa",
  "zh": "中文"
};
